In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("NLP dataset/Emotion_classify_Data.csv")

In [3]:
data.head()

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [4]:
data['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [5]:
data.shape

(5937, 2)

In [11]:
#data["output"]=data["Emotion"].apply(lambda x:1 if x=='anger' x:2 if x=='fear' else 0 )
data["output"] = data["Emotion"].apply(
    lambda x: 1 if x == 'anger' else 2 if x == 'fear' else 0
)

In [12]:
data

                                                Comment Emotion  output
0     i seriously hate one subject to death but now ...    fear       2
1                    im so full of life i feel appalled   anger       1
2     i sit here to write i start to dig out my feel...    fear       2
3     ive been really angry with r and i feel like a...     joy       0
4     i feel suspicious if there is no one outside l...    fear       2
...                                                 ...     ...     ...
5932                 i begun to feel distressed for you    fear       2
5933  i left feeling annoyed and angry thinking that...   anger       1
5934  i were to ever get married i d have everything...     joy       0
5935  i feel reluctant in applying there because i w...    fear       2
5936  i just wanted to apologize to you because i fe...   anger       1

[5937 rows x 3 columns]

In [13]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer,WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\win11\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\win11\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\win11\AppData\Roaming\nltk_data...

True

In [15]:
ps=PorterStemmer()
lemmatizer=WordNetLemmatizer()
stopwords=set(stopwords.words('english'))

In [ ]:
#tokenization preprocessing part 1
data['tokenn']=data['Comment'].apply(word_tokenize)

In [19]:
data.head()

,Comment,Emotion,output,token,tokenn
0,i seriously hate one subject to death but now ...,fear,2,[fear],"[i, seriously, hate, one, subject, to, death, ..."
1,im so full of life i feel appalled,anger,1,[anger],"[im, so, full, of, life, i, feel, appalled]"
2,i sit here to write i start to dig out my feel...,fear,2,[fear],"[i, sit, here, to, write, i, start, to, dig, o..."
3,ive been really angry with r and i feel like a...,joy,0,[joy],"[ive, been, really, angry, with, r, and, i, fe..."
4,i feel suspicious if there is no one outside l...,fear,2,[fear],"[i, feel, suspicious, if, there, is, no, one, ..."

In [21]:
#stopwords
data['stopwords']=data['tokenn'].apply(lambda x:[word.lower() for word in x if word.lower() not in stopwords and word.isalpha()])

In [22]:
len(data['tokenn'].iloc[5])

20

In [23]:
len(data['stopwords'].iloc[5])

11

In [24]:
#preprocessing la part 3 stemming 
data['steamming']=data['stopwords'].apply(lambda x:[ps.stem(word) for word in x])

In [25]:
data.head()

,Comment,Emotion,output,token,tokenn,stopwords,steamming
0,i seriously hate one subject to death but now ...,fear,2,[fear],"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel..."
1,im so full of life i feel appalled,anger,1,[anger],"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]"
2,i sit here to write i start to dig out my feel...,fear,2,[fear],"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ..."
3,ive been really angry with r and i feel like a...,joy,0,[joy],"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru..."
4,i feel suspicious if there is no one outside l...,fear,2,[fear],"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap..."

In [ ]:
#lemmatization

#data['lemma']=data['stopwords'].apply(lambda x:[lemmatizer.lemmatize(word) for word in x])

In [26]:
data['steamming'].iloc[2]

['sit',
 'write',
 'start',
 'dig',
 'feel',
 'think',
 'afraid',
 'accept',
 'possibl',
 'might',
 'make']

In [27]:
data.head()

,Comment,Emotion,output,token,tokenn,stopwords,steamming
0,i seriously hate one subject to death but now ...,fear,2,[fear],"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel..."
1,im so full of life i feel appalled,anger,1,[anger],"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]"
2,i sit here to write i start to dig out my feel...,fear,2,[fear],"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ..."
3,ive been really angry with r and i feel like a...,joy,0,[joy],"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru..."
4,i feel suspicious if there is no one outside l...,fear,2,[fear],"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap..."

In [29]:
#corrected to join the actual lemmas or steamming 

data['processed_text']=data['steamming'].apply(lambda x:" ".join(x))

In [30]:
data.head()

,Comment,Emotion,output,token,tokenn,stopwords,steamming,processed_text
0,i seriously hate one subject to death but now ...,fear,2,[fear],"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...",serious hate one subject death feel reluct drop
1,im so full of life i feel appalled,anger,1,[anger],"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]",im full life feel appal
2,i sit here to write i start to dig out my feel...,fear,2,[fear],"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...",sit write start dig feel think afraid accept p...
3,ive been really angry with r and i feel like a...,joy,0,[joy],"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...",ive realli angri r feel like idiot trust first...
4,i feel suspicious if there is no one outside l...,fear,2,[fear],"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...",feel suspici one outsid like raptur happen someth

In [31]:
#part 3
vectorizer=CountVectorizer()
x=vectorizer.fit_transform(data['processed_text'])

In [32]:
data.head()

,Comment,Emotion,output,token,tokenn,stopwords,steamming,processed_text
0,i seriously hate one subject to death but now ...,fear,2,[fear],"[i, seriously, hate, one, subject, to, death, ...","[seriously, hate, one, subject, death, feel, r...","[serious, hate, one, subject, death, feel, rel...",serious hate one subject death feel reluct drop
1,im so full of life i feel appalled,anger,1,[anger],"[im, so, full, of, life, i, feel, appalled]","[im, full, life, feel, appalled]","[im, full, life, feel, appal]",im full life feel appal
2,i sit here to write i start to dig out my feel...,fear,2,[fear],"[i, sit, here, to, write, i, start, to, dig, o...","[sit, write, start, dig, feelings, think, afra...","[sit, write, start, dig, feel, think, afraid, ...",sit write start dig feel think afraid accept p...
3,ive been really angry with r and i feel like a...,joy,0,[joy],"[ive, been, really, angry, with, r, and, i, fe...","[ive, really, angry, r, feel, like, idiot, tru...","[ive, realli, angri, r, feel, like, idiot, tru...",ive realli angri r feel like idiot trust first...
4,i feel suspicious if there is no one outside l...,fear,2,[fear],"[i, feel, suspicious, if, there, is, no, one, ...","[feel, suspicious, one, outside, like, rapture...","[feel, suspici, one, outsid, like, raptur, hap...",feel suspici one outsid like raptur happen someth

In [33]:
words=vectorizer.get_feature_names_out()

In [34]:
print(words)

['aa' 'aac' 'aaron' ... 'zonisamid' 'zq' 'zumba']

In [35]:
bow=pd.DataFrame(x.toarray(),columns=words)

In [36]:
print(bow.head())

   aa  aac  aaron  ab  abandon  abbigail  abc  abdomen  abelard  abid  ...  \
0   0    0      0   0        0         0    0        0        0     0  ...
1   0    0      0   0        0         0    0        0        0     0  ...
2   0    0      0   0        0         0    0        0        0     0  ...
3   0    0      0   0        0         0    0        0        0     0  ...
4   0    0      0   0        0         0    0        0        0     0  ...

   zendikar  zero  zest  zhu  ziplin  zombi  zone  zonisamid  zq  zumba
0         0     0     0    0       0      0     0          0   0      0
1         0     0     0    0       0      0     0          0   0      0
2         0     0     0    0       0      0     0          0   0      0
3         0     0     0    0       0      0     0          0   0      0
4         0     0     0    0       0      0     0          0   0      0

[5 rows x 6319 columns]

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(bow,data['output'],test_size=0.2,random_state=42)

In [39]:
x_train.shape

(4749, 6319)

In [41]:
x_test.shape

(1188, 6319)

In [42]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9402356902356902
[[360   9  11]
 [ 14 371   7]
 [ 10  20 386]]
              precision    recall  f1-score   support

           0       0.94      0.95      0.94       380
           1       0.93      0.95      0.94       392
           2       0.96      0.93      0.94       416

    accuracy                           0.94      1188
   macro avg       0.94      0.94      0.94      1188
weighted avg       0.94      0.94      0.94      1188

In [44]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_test,y_test)
y_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9974747474747475
[[380   0   0]
 [  0 389   3]
 [  0   0 416]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       380
           1       1.00      0.99      1.00       392
           2       0.99      1.00      1.00       416

    accuracy                           1.00      1188
   macro avg       1.00      1.00      1.00      1188
weighted avg       1.00      1.00      1.00      1188

In [45]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.8947811447811448
[[325  26  29]
 [ 14 360  18]
 [ 15  23 378]]
              precision    recall  f1-score   support

           0       0.92      0.86      0.89       380
           1       0.88      0.92      0.90       392
           2       0.89      0.91      0.90       416

    accuracy                           0.89      1188
   macro avg       0.90      0.89      0.89      1188
weighted avg       0.90      0.89      0.89      1188

In [50]:
from sklearn.naive_bayes import MultinomialNB
nb=MultinomialNB(alpha=17)
nb.fit(x_test,y_test)
y_pred=nb.predict(x_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9141414141414141
[[318  13  49]
 [  5 362  25]
 [  2   8 406]]
              precision    recall  f1-score   support

           0       0.98      0.84      0.90       380
           1       0.95      0.92      0.93       392
           2       0.85      0.98      0.91       416

    accuracy                           0.91      1188
   macro avg       0.92      0.91      0.91      1188
weighted avg       0.92      0.91      0.91      1188